name: Deploy to GitHub Pages

on:
  push:
      branches: [ master ]
      
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'
        
    - name: Publish .NET Project
      run: dotnet workload install wasm-tools && dotnet publish GEDCOM-Viewer/GEDCOM-Viewer.csproj -c Release -o release --nologo
        
    - name: Change base-tag in index.html from / to /{repo name}
      run: sed -i 's/<base href="\/" \/>/<base href="\/gedcom-viewer\/" \/>/g' release/wwwroot/index.html
    
    - name: Patch blazor.webassembly.js
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "return r.loadResource\\(o,t\\(o\\),e\\[o\\],n\\)"
        replace: "var p = r.loadResource(o,t(o),e[o],n); p.response.then((x) => { if (typeof window.loadResourceCallback === 'function') { window.loadResourceCallback(Object.keys(e).length, o, x);}}); return p;"
        include: "release/wwwroot/_framework/blazor.webassembly.js"
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: release/wwwroot
